#!/bin/bash
yum update -y
yum install -y httpd
service httpd start
chkconfig httpd on
groupadd www
usermod -a -G www ec2-user
chown -R root:www /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} +
find /var/www -type f -exec chmod 0664 {} +
echo "site of @peter_v" > /var/www/html/index.html
echo ` echo `curl 169.254.169.254/latest/meta-data/local-ipv4` >> /var/www/html/index.html`
echo "success" > /var/www/html/healthcheck.html
echo "alias l='ls -l'" >> .bashrc
echo "alias l='ls -l'" >> /home/ec2-user/.bashrc
